LKE-5884 feat (autoRange): Handle logarithmic function
Linkurious/ogma-linkurious-parser pull request #171
Opened 2022-04-07 13:35 UTC by Kraamel

We want to be able to use the autoRange with either a linear (default) or a logarithmic function

2022-04-11 08:31 UTC, aminerhanemi commented on src/styles/edgeAttributes.ts
> +          return widthStyle.scale && widthStyle.scale === 'logarithmic'
This three lines can be replaced with.
```
const isLog = widthStyle.scale && widthStyle.scale === 'logarithmic'
return EdgeAttributes.getAutomaticRangeWidth(propertyValue, styleRule, isLog)
```

What do you think ?

2022-04-11 08:36 UTC, aminerhanemi commented on src/styles/itemAttributes.ts
> +      value += -min + 1;
it is better to use absolute value than -min in case min is between 0 and 1.
```suggestion
      value += Math.abs(min)+ 1;
```

2022-04-11 08:37 UTC, aminerhanemi commented on src/styles/itemAttributes.ts
> +      min = 1;
same

2022-04-11 08:38 UTC, aminerhanemi commented on src/styles/nodeAttributes.ts
> +  private static matchStyle(
unit test if it is possible

2022-04-11 08:39 UTC, aminerhanemi commented on src/styles/nodeAttributes.ts
> +            result =
Same comment as edges

2022-04-11 14:16 UTC, aminerhanemi commented on src/styles/itemAttributes.ts
> +    // apply an offset for all the values (including max) if min is smaller than one and set min to 1
// apply an offset for all the values (including min and max)

2022-04-13 11:36 UTC, aminerhanemi requested changes

2022-04-13 11:36 UTC, aminerhanemi commented on tests/styles/edgeAttributes.spec.ts
> +      expect(
can you add test with negative value

2022-04-13 11:36 UTC, aminerhanemi commented on tests/styles/nodeAttributes.spec.ts
> +        NodeAttributes.getAutomaticRangeSize(
same

2022-04-13 12:50 UTC, Kraamel commented on tests/styles/edgeAttributes.spec.ts
> +      expect(
done

2022-04-13 12:50 UTC, Kraamel commented on tests/styles/nodeAttributes.spec.ts
> +        NodeAttributes.getAutomaticRangeSize(
done

2022-04-13 13:49 UTC, aminerhanemi approved these changes

2022-04-22 08:33 UTC, merged